name: Publish

on:
  push:
    branches:
      - master
    paths:
      # Bộ lọc mới: Kích hoạt khi code worker hoặc dependencies gốc thay đổi
      - 'app/workers/**'
      - 'package.json' 
      - 'package-lock.json' 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    if: github.event_name != 'workflow_dispatch' || github.actor == 'alikuxac'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"

      - name: Install Monorepo Dependencies
        run: npm ci --silent 

      - name: Deploy Worker (app/workers)
        working-directory: app/workers
        run: npm run deploy > /dev/null 2>&1
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}